name = input ("Type your name ")
print("Hello",name)
surname = input ("Type your surname ")
print("Hello",name,surname)
number1 = int(input("Enter a number "))
number2 = int(input("Enter another number "))
print(number1+number2)
numbcollect = (number1+number2)
number3 = int(input("Enter a third number "))
print(numbcollect*number3)
slicestarted =  int(input("How many slices of pizza have you started with "))
sliceate = int(input("How many slices of pizza have you eaten "))
print ("You have",slicestarted-sliceate,"slices left")
age = int(input("What's your age "))
print ("Next year you will be",age+1,"years old!")
bill = int(input("How much is the bill "))
diners = int(input("How many people are dining "))
print ("Each person should pay",bill/diners,"euro")
days = int(input("Say a number of days "))
seconds = 0
minutes = 0
print ("Days:",(24*days),"Seconds:",(seconds),"Minutes:",(minutes))
kg = int(input("Enter a weight in kilograms "))
print("Heres your weight in pounds ",kg*2.204)
       